name: paynote
description: "PayNote - Smart USSD helper and transaction tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  contacts_service: ^0.6.3
  url_launcher: ^6.2.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  path: ^1.8.3
  fl_chart: ^0.65.0
  csv: ^5.0.2
  pdf: ^3.10.7
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
